var CreateEventButton = document.getElementById("CreateEventButton");
var CreateEventBody = document.getElementById("CreateEventBody");
var SaveTheDateButton = document.getElementById("SaveTheDateButton");
var SaveTheDateBody = document.getElementById("SaveTheDateBody");
var TypeButton = document.getElementById("TypeButton");
var TypeBody = document.getElementById("TypeBody");
var GuestListButton = document.getElementById("GuestListButton");
var GuestListBody = document.getElementById("GuestListBody");
var VenueButton = document.getElementById("VenueButton");
var VenueBody = document.getElementById("VenueBody");
var ProvisionsButton = document.getElementById("ProvisionsButton");
var ProvisionsBody = document.getElementById("ProvisionsBody");
var CreateEventSide = document.getElementById("CreateEventSide")

var CommunityBtn = document.getElementById("CommunityBtn");
var CommunityArea = document.getElementById("CommunityArea");
var SocialBtn = document.getElementById("SocialBtn");
var SocialArea = document.getElementById("SocialArea")
var TournamentBtn = document.getElementById("TournamentBtn");
var TournamentArea = document.getElementById("TournamentArea")
var FundraiserBtn = document.getElementById("FundraiserBtn");
var FundraiserArea = document.getElementById("FundraiserArea")
var FestivalBtn = document.getElementById("FestivalBtn");
var FestivalArea = document.getElementById("FestivalArea")
var OtherBtn = document.getElementById("OtherBtn");
var OtherArea = document.getElementById("OtherArea")
var OtherOptsArea = document.getElementById("OtherOptsArea");
var EventType = 0

var d = new Date();
var D = d.getDate();
var WD = d.getDay();
var Y = d.getFullYear();
var M = d.getMonth();
var LY = Math.abs(Y - 2024);
var mult4val = 0;
var mult4 = [];
var Mmax = 0;
var singleDate = 1;
var weekDay = WD;
var monthsArray = [];
var weekDayStart = 0;
var weekDayEnd = 0;
var preMonthDate = 0;
var nextMonthDate = 0;
var duringMonthDates = 0;
var calMonthStartWD = 0;
var calMonthEndWD = 0;
var calMonthStartD = 0;
var calMonthEndD = 0;
var pairD = 0;
var pairWD = 0;
var pairWDkept = 0;
var pairDkept = 0;
var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
